import Foundation

enum MessageIDGenerator {
    static let outboundDomain = "app-feedback.local"
    private static let syntheticDomain = "imap-synthetic"
    /// Encoded issue context lives at the start of the local-part:
    /// `af~{owner}~{repo}~{number}~{uuid}@app-feedback.local`. The tilde separator
    /// avoids collisions with hyphens and dots that GitHub permits in owner/repo names.
    private static let issuePrefix = "af~"
    private static let issueSeparator: Character = "~"

    /// Generate a Message-Id. When repo + issue context is supplied, the issue identity is
    /// embedded so backfill can restore the thread→issue association from the Sent folder
    /// after a Reset (no extra IMAP round-trips, no custom headers).
    static func generate(
        repoOwner: String? = nil,
        repoName: String? = nil,
        issueNumber: Int? = nil
    ) -> String {
        let uuid = UUID().uuidString.lowercased()
        if let owner = repoOwner, let repo = repoName, let number = issueNumber,
           !owner.isEmpty, !repo.isEmpty, number > 0 {
            return "<\(issuePrefix)\(owner)~\(repo)~\(number)~\(uuid)@\(outboundDomain)>"
        }
        return "<\(uuid)@\(outboundDomain)>"
    }

    /// Returns `(owner, repo, number)` if `messageID` was generated by this app from a
    /// known issue context. Returns nil for plain outbound IDs, synthetic IDs, or any
    /// Message-Id that didn't originate here (incoming mail, Gmail-rewritten, etc.).
    static func parseIssueContext(from messageID: String) -> (owner: String, repo: String, number: Int)? {
        var s = messageID
        if s.hasPrefix("<") { s.removeFirst() }
        if s.hasSuffix(">") { s.removeLast() }
        guard let atIdx = s.lastIndex(of: "@") else { return nil }
        let local = String(s[..<atIdx])
        let domain = String(s[s.index(after: atIdx)...])
        guard domain == outboundDomain, local.hasPrefix(issuePrefix) else { return nil }
        let body = local.dropFirst(issuePrefix.count)
        let parts = body.split(separator: issueSeparator, maxSplits: 3, omittingEmptySubsequences: false)
        guard parts.count == 4, let number = Int(parts[2]), number > 0,
              !parts[0].isEmpty, !parts[1].isEmpty else { return nil }
        return (owner: String(parts[0]), repo: String(parts[1]), number: number)
    }

    static func isSynthetic(_ messageID: String) -> Bool {
        messageID.contains("@\(syntheticDomain)")
    }

    /// Synthesises a stable Message-ID from an IMAP UID + UIDValidity pair.
    /// Format: `<uid-{uid}.{uidValidity}@imap-synthetic>`
    static func synthesize(uid: UInt32, uidValidity: UInt32) -> String {
        "<uid-\(uid).\(uidValidity)@\(syntheticDomain)>"
    }
}

enum MailAddress {
    /// Reduce a recipient string to just `addr@domain`. Handles the common forms:
    /// - `Display Name <addr@x>` → `addr@x`
    /// - `"Quoted Name" <addr@x>` → `addr@x`
    /// - `addr@x` (already bare) → `addr@x`
    /// Returns nil for inputs that don't yield a plain ASCII address — SMTP rejects those,
    /// and Gmail's IMAP SEARCH rejects non-ASCII string literals with `BAD Could not parse`.
    static func bare(from raw: String) -> String? {
        var s = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        if let lt = s.lastIndex(of: "<"), let gt = s.lastIndex(of: ">"), lt < gt {
            s = String(s[s.index(after: lt)..<gt])
        }
        s = s.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !s.isEmpty,
              s.contains("@"),
              s.allSatisfy({ $0.isASCII && !$0.isWhitespace }) else { return nil }
        return s
    }
}
