#if DEBUG
import Foundation
import LoveLetterCore

/// The demo content. Plain data, kept apart from the seeding engine so copy edits never touch
/// logic. Rules the tests enforce:
/// - every product mixes all three sources and has one non-English item;
/// - tasks cover every status and priority and reference existing feedback numbers;
/// - each product has a released, a WIP (a started task in its milestone) and a new version;
/// - emails are @example.com; no attachments; no App Store / inbox / connected-repo wiring.
extension MockDataSeeder {
    static let products: [ProductSpec] = [pixelJournal, tidyBudget, trailBuddy]

    /// Reply templates, seeded into every product.
    static let replyTemplates: [(title: String, body: String)] = [
        ("Thanks — we're on it",
         "Thanks so much for taking the time to write in! I've reproduced this and a fix is being worked on now. I'll let you know as soon as it ships."),
        ("Fixed in the latest update",
         "Good news: this is fixed in the update that just went out. Please update from the App Store and let me know if you still see it."),
        ("Feature request noted",
         "Love this idea — I've added it to our list for an upcoming version. Thanks for helping shape the app!"),
    ]

    // MARK: Pixel Journal (iOS journaling app)

    static let pixelJournal = ProductSpec(
        id: UUID(uuidString: "6F1C2A10-0000-4000-8000-000000000001")!,
        displayName: "Pixel Journal", repo: "pixel-journal", colorHex: "7b8cff",
        feedback: [
            FeedbackSpec(number: 1, title: "Photos disappear after editing an entry",
                         text: "I added three photos to yesterday's entry, then fixed a typo in the text. After saving, only the first photo is left. Happens every time I edit an entry with more than one photo.",
                         origin: .sdk(type: .bug, appVersion: "2.3.0", build: "231", device: "iPhone17,1", osName: "iOS", osVersion: "27.0", email: "maya.chen@example.com"),
                         hoursAgo: 3),
            FeedbackSpec(number: 2, title: "Dark mode for the calendar view",
                         text: "The calendar is still bright white when the rest of the app is dark. Writing at night it's really glaring.",
                         origin: .sdk(type: .featureRequest, appVersion: "2.3.0", build: "231", device: "iPad16,3", osName: "iPadOS", osVersion: "27.0", email: nil),
                         hoursAgo: 9),
            FeedbackSpec(number: 3, title: "Finally a journal I stick with",
                         text: "The daily prompts and streaks got me writing every day for two months now. Stickers are adorable.",
                         origin: .appStore(rating: 5, territory: "USA", nickname: "sunnyday_writes"),
                         hoursAgo: 20),
            FeedbackSpec(number: 4, title: "Sync lost a week of entries",
                         text: "Switched to a new iPhone and everything from last week is gone. Please help, those entries matter to me.",
                         origin: .appStore(rating: 2, territory: "GBR", nickname: "tomk"),
                         hoursAgo: 30),
            FeedbackSpec(number: 5, title: "Export to PDF?",
                         text: "Hi! Is there a way to export a whole year as a PDF? I'd love to print a book of my entries for my mum.",
                         origin: .email(from: "r.alvarez@example.com"),
                         hoursAgo: 44),
            FeedbackSpec(number: 6, title: "App stürzt beim Öffnen alter Einträge ab",
                         text: "Seit dem letzten Update stürzt die App jedes Mal ab, wenn ich einen Eintrag vom letzten Jahr öffne. Neuere Einträge funktionieren ohne Probleme.",
                         origin: .sdk(type: .bug, appVersion: "2.3.0", build: "231", device: "iPhone16,2", osName: "iOS", osVersion: "26.4", email: "lena.m@example.com"),
                         hoursAgo: 52),
            FeedbackSpec(number: 7, title: "Can I lock individual entries with Face ID?",
                         text: "Some entries are private. Could I lock just those behind Face ID instead of the whole app?",
                         origin: .sdk(type: .featureRequest, appVersion: "2.2.1", build: "220", device: "iPhone15,4", osName: "iOS", osVersion: "26.4", email: nil),
                         extraLabels: ["question"],
                         hoursAgo: 70),
            FeedbackSpec(number: 8, title: "Lovely, wish it had widgets",
                         text: "Beautiful app. A home-screen widget with today's prompt would make it perfect.",
                         origin: .appStore(rating: 4, territory: "CAN", nickname: "maplewrites"),
                         hoursAgo: 96),
        ],
        tasks: [
            TaskSpec(number: 9, title: "Keep all photos when saving an edited entry",
                     notes: "The edit flow rebuilds the attachment list from the first photo only.",
                     status: .inProgress, priority: .high, milestone: "2.4.0", refs: [1], hoursAgo: 26),
            TaskSpec(number: 10, title: "Investigate lost entries after device migration",
                     notes: "Check whether the CloudKit zone is reset on the first launch of a restored device.",
                     status: .todo, priority: .high, milestone: "2.4.0", refs: [4], hoursAgo: 28),
            TaskSpec(number: 11, title: "Dark calendar theme",
                     notes: "Match the calendar grid to the system appearance.",
                     status: .todo, priority: .med, milestone: "2.5.0", refs: [2], hoursAgo: 60),
            TaskSpec(number: 12, title: "Export a date range as PDF",
                     notes: "Paginated PDF with photos; share sheet on iOS.",
                     status: .todo, priority: .low, milestone: nil, refs: [5], hoursAgo: 80),
            TaskSpec(number: 13, title: "Fix crash opening entries from 2025",
                     notes: "A legacy date format in old entries crashes the decoder.",
                     status: .done, priority: .high, milestone: "2.3.0", refs: [6], hoursAgo: 200),
            TaskSpec(number: 14, title: "Per-entry Face ID lock",
                     notes: "LocalAuthentication gate on entries marked private.",
                     status: .todo, priority: .med, milestone: "2.5.0", refs: [7], hoursAgo: 100),
        ],
        versions: [
            VersionSpec(name: "2.3.0", title: "Stickers & streaks",
                        changelog: "- Sticker packs for entries\n- Writing streaks\n- Fixed a crash when opening entries from 2025",
                        released: true, daysAgo: 40),
            VersionSpec(name: "2.4.0", title: "Sync you can trust",
                        changelog: "- Photos survive edits\n- Safer sync after moving to a new device",
                        released: false, daysAgo: 12),
            VersionSpec(name: "2.5.0", title: "Night owl",
                        changelog: "- Dark calendar\n- Face ID lock for private entries",
                        released: false, daysAgo: 2),
        ])

    // MARK: Tidy Budget (Mac + iPhone budgeting app)

    static let tidyBudget = ProductSpec(
        id: UUID(uuidString: "6F1C2A10-0000-4000-8000-000000000002")!,
        displayName: "Tidy Budget", repo: "tidy-budget", colorHex: "34d399",
        feedback: [
            FeedbackSpec(number: 1, title: "CSV import skips rows with commas in the payee",
                         text: "Importing my bank's CSV drops every row where the payee has a comma, like \"Smith, J\". Quoted fields should be kept.",
                         origin: .sdk(type: .bug, appVersion: "1.8.0", build: "180", device: "Mac16,1", osName: "macOS", osVersion: "27.0", email: "dev.ops@example.com"),
                         hoursAgo: 2),
            FeedbackSpec(number: 2, title: "Shared budgets with my partner",
                         text: "We'd love to share one household budget and both add expenses from our own phones.",
                         origin: .sdk(type: .featureRequest, appVersion: "1.8.0", build: "180", device: "iPhone17,3", osName: "iOS", osVersion: "27.0", email: nil),
                         hoursAgo: 8),
            FeedbackSpec(number: 3, title: "Subscription charged twice",
                         text: "I was billed twice this month for the yearly plan. Please refund one of them.",
                         origin: .appStore(rating: 1, territory: "USA", nickname: "budgetbuddy88"),
                         hoursAgo: 15),
            FeedbackSpec(number: 4, title: "Best budgeting app on the Mac",
                         text: "Fast, native, and the reports are gorgeous. Worth every cent.",
                         origin: .appStore(rating: 5, territory: "AUS", nickname: "koala_cash"),
                         hoursAgo: 27),
            FeedbackSpec(number: 5, title: "Question about bank sync",
                         text: "Does Tidy Budget connect to my bank directly, or do I always need to import files?",
                         origin: .email(from: "samir@example.com"),
                         extraLabels: ["question"],
                         hoursAgo: 40),
            FeedbackSpec(number: 6, title: "Los totales mensuales no coinciden",
                         text: "El resumen de septiembre muestra un total distinto al de la lista de transacciones. Faltan unos cuarenta euros y no encuentro por qué.",
                         origin: .sdk(type: .bug, appVersion: "1.8.0", build: "180", device: "Mac15,12", osName: "macOS", osVersion: "26.4", email: "lucia.g@example.com"),
                         hoursAgo: 55),
            FeedbackSpec(number: 7, title: "Keyboard shortcut to add a transaction",
                         text: "Please add Command-N for a new transaction. I enter dozens a week and always reach for the mouse.",
                         origin: .sdk(type: .featureRequest, appVersion: "1.7.2", build: "172", device: "Mac16,10", osName: "macOS", osVersion: "26.4", email: nil),
                         hoursAgo: 75),
        ],
        tasks: [
            TaskSpec(number: 8, title: "Handle quoted commas in CSV import",
                     notes: "RFC 4180 quoting in the importer.",
                     status: .done, priority: .high, milestone: "1.8.0", refs: [1], hoursAgo: 300),
            TaskSpec(number: 9, title: "Shared budgets via CloudKit sharing",
                     notes: "CKShare for the household budget zone.",
                     status: .inProgress, priority: .med, milestone: "1.9.0", refs: [2], hoursAgo: 30),
            TaskSpec(number: 10, title: "Investigate duplicate subscription charge",
                     notes: "Check StoreKit transaction history for double renewals.",
                     status: .todo, priority: .high, milestone: nil, refs: [3], hoursAgo: 14),
            TaskSpec(number: 11, title: "Reconcile monthly totals with the transaction list",
                     notes: "The summary excludes split transactions.",
                     status: .todo, priority: .med, milestone: "2.0.0", refs: [6], hoursAgo: 50),
            TaskSpec(number: 12, title: "Command-N adds a transaction",
                     notes: "Menu command plus toolbar button.",
                     status: .inProgress, priority: .low, milestone: "1.9.0", refs: [7], hoursAgo: 60),
        ],
        versions: [
            VersionSpec(name: "1.8.0", title: "Clean imports",
                        changelog: "- CSV import keeps quoted payees\n- Faster reports",
                        released: true, daysAgo: 35),
            VersionSpec(name: "1.9.0", title: "Better together",
                        changelog: "- Shared household budgets\n- Command-N for a new transaction",
                        released: false, daysAgo: 10),
            VersionSpec(name: "2.0.0", title: "Tidy 2",
                        changelog: "- Monthly totals include split transactions",
                        released: false, daysAgo: 1),
        ])

    // MARK: Trail Buddy (iPhone + Watch hiking app)

    static let trailBuddy = ProductSpec(
        id: UUID(uuidString: "6F1C2A10-0000-4000-8000-000000000003")!,
        displayName: "Trail Buddy", repo: "trail-buddy", colorHex: "ffb347",
        feedback: [
            FeedbackSpec(number: 1, title: "GPS track drifts under tree cover",
                         text: "In dense forest my recorded track zig-zags up to 50 m off the trail, so the distance ends up way too long.",
                         origin: .sdk(type: .bug, appVersion: "3.1.0", build: "310", device: "iPhone17,1", osName: "iOS", osVersion: "27.0", email: "hiker.jo@example.com"),
                         hoursAgo: 1),
            FeedbackSpec(number: 2, title: "Great maps, battery drain is rough",
                         text: "Love the topo maps, but a five-hour hike eats seventy percent of my battery.",
                         origin: .appStore(rating: 3, territory: "DEU", nickname: "alpenwanderer"),
                         hoursAgo: 12),
            FeedbackSpec(number: 3, title: "Saved me on a foggy ridge",
                         text: "Lost the trail in thick fog and the offline map got me back to the hut. Thank you!",
                         origin: .appStore(rating: 5, territory: "NZL", nickname: "kiwi_tramper"),
                         hoursAgo: 22),
            FeedbackSpec(number: 4, title: "Offline maps for whole national parks",
                         text: "Downloading tile by tile is tedious. Let me grab an entire park before a trip.",
                         origin: .sdk(type: .featureRequest, appVersion: "3.1.0", build: "310", device: "iPad14,8", osName: "iPadOS", osVersion: "27.0", email: nil),
                         hoursAgo: 34),
            FeedbackSpec(number: 5, title: "Apple Watch complication request",
                         text: "Could you add a watch face complication showing distance and elevation gain?",
                         origin: .email(from: "p.nakamura@example.com"),
                         hoursAgo: 48),
            FeedbackSpec(number: 6, title: "L'altitude affichée est fausse",
                         text: "Sur le sentier du Mont Blanc, l'altitude affichée est décalée d'environ deux cents mètres par rapport aux panneaux.",
                         origin: .sdk(type: .bug, appVersion: "3.1.0", build: "310", device: "iPhone17,3", osName: "iOS", osVersion: "26.4", email: "camille.d@example.com"),
                         hoursAgo: 58),
            FeedbackSpec(number: 7, title: "Workout doesn't end when I stop on the watch",
                         text: "Ending the hike on my watch leaves the workout running on the phone until I open the app.",
                         origin: .sdk(type: .bug, appVersion: "3.0.4", build: "304", device: "Watch7,1", osName: "watchOS", osVersion: "26.4", email: nil),
                         hoursAgo: 66),
            FeedbackSpec(number: 8, title: "Can I share my live location with friends?",
                         text: "Would be great for solo hikes: a link my partner can open to see where I am.",
                         origin: .sdk(type: .featureRequest, appVersion: "3.1.0", build: "310", device: "iPhone16,2", osName: "iOS", osVersion: "27.0", email: nil),
                         extraLabels: ["question"],
                         hoursAgo: 90),
        ],
        tasks: [
            TaskSpec(number: 9, title: "Smooth GPS tracks under canopy",
                     notes: "Kalman filter plus horizontal-accuracy gating.",
                     status: .inProgress, priority: .high, milestone: "3.2.0", refs: [1], hoursAgo: 20),
            TaskSpec(number: 10, title: "Cut background location battery use",
                     notes: "Adaptive sampling when speed is steady.",
                     status: .inProgress, priority: .high, milestone: "3.2.0", refs: [2], hoursAgo: 24),
            TaskSpec(number: 11, title: "Offline map packs per national park",
                     notes: "Region download with progress and a storage estimate.",
                     status: .todo, priority: .med, milestone: "3.3.0", refs: [4], hoursAgo: 40),
            TaskSpec(number: 12, title: "Watch complication: distance & elevation",
                     notes: "WidgetKit accessory families.",
                     status: .todo, priority: .low, milestone: "3.3.0", refs: [5, 8], hoursAgo: 45),
            TaskSpec(number: 13, title: "Calibrate barometric altitude",
                     notes: "Use DEM elevation at the trail start as the reference.",
                     status: .done, priority: .high, milestone: "3.1.0", refs: [6], hoursAgo: 400),
            TaskSpec(number: 14, title: "End the phone workout when the watch ends it",
                     notes: "Observe the HKWorkoutSession state on the phone.",
                     status: .done, priority: .med, milestone: "3.2.0", refs: [7], hoursAgo: 35),
        ],
        versions: [
            VersionSpec(name: "3.1.0", title: "Summit",
                        changelog: "- Accurate barometric altitude\n- New topo map style",
                        released: true, daysAgo: 50),
            VersionSpec(name: "3.2.0", title: "All-day battery",
                        changelog: "- Smoother GPS tracks under trees\n- Lower battery use\n- Watch ends the phone workout",
                        released: false, daysAgo: 14),
            VersionSpec(name: "3.3.0", title: "Off the grid",
                        changelog: "- National park map packs\n- Watch complication",
                        released: false, daysAgo: 3),
        ])
}
#endif
